### PR TITLE
Real Fix issue with SSR

### PR DESCRIPTION
**Pull request by igorkamyshev**
Hello. Great lib.

I found #7 PR, but it was not approved and also will not fix the problem (because isClient calculate once and listener not apply).

Please, review my solution and give me your feedback.

### CODE REVIEW

**Comment by igorkamyshev** [comment]
@jamiebuilds hello 🤓

**Comment by igorkamyshev** [comment]
@iamsolankiamit hello, maybe you can review this PR?

**Comment by iamsolankiamit** [comment]
Ahh! didn't get notified about this somehow. Reviewing

**Review by iamsolankiamit — APPROVED** [review]

**Comment by iamsolankiamit** [comment]
I won't be able to merge it though, only @jamiebuilds can.

**Comment by igorkamyshev** [comment]
@iamsolankiamit thanks 🙆‍♂️ 

@jamiebuilds hey 🙏

**Comment by igorkamyshev** [comment]
@jamiebuilds hello? What about PR? =)

**Comment by igorkamyshev** [comment]
@jamesplease hop-hey!

**Comment by jamesplease** [comment]
lgtm; I'm also unable to merge, though.

**Review by jamesplease — APPROVED** [review]

**Comment by igorkamyshev** [comment]
Hmm
 Who can merge it? 😅

**Comment by igorkamyshev** [comment]
Okay.

**Pull request closed without merging**
